### ISSUE TITLE
Fix bibliography formatting

### ISSUE THREAD

**Issue by cdeil** [gammapy/icrc2017-gammapy-poster#2]
Comment by Julien and Catherine:
```
beware, all the arxiv references are WRONG

- ref 3: arxiv should be within []
- ref 5: Lefaucheur
- ref 10: 1507.03989
- ref 11: 1509.03319
- ref 12: Chandra
- ref 14: LSST and with Astropy
- ref 15: 1606.00393
- ref 16: 1507.08343
- ref 17: 1610.01884
- ref 23: 1509.07408
```

I've done ref 5 just now. For the others, I don't know how to do it, I'm not good with LaTeX.
The ArXiV identifiers and the capitalisation are OK in the bibtex file.
So there must be some issue with this:
```
\bibliographystyle{JHEP}
```
https://github.com/gammapy/icrc2017-gammapy-poster/blob/a0a557ff057f3cb764cd67833468b58bc212f6d9/proceeding/gammapy-icrc2017.tex#L363

@jjlk - Can you implement a fix or workaround? Or do you have a suggestion what to try?

**Comment by jjlk** [comment]
Hi @cdeil  and @joleroi, 
I think that one digit is missing in the Arxiv identifier. I do not have time at all to fix the references.

**Comment by cdeil** [comment]
@jjlk - No.

E.g. at https://github.com/gammapy/icrc2017-gammapy-poster/blob/master/proceeding/gammapy-icrc2017.bib#L54 we have the correct
```
Eprint = {1509.03319},
```
but then in the PDF the last digit "9" is missing.
!?

**Comment by cdeil** [comment]
So JHEP is the recommended style with PoS when using bibtex: https://pos.sissa.it/PoSauthmanual.pdf

I had an old version, updating `JHEP.bst` to version 2.6 fixes the incorect ArXiV IDs:
https://jhep.sissa.it/jhep/help/JHEP/TeXclass/DOCS/JHEP.bst

Putting the new version, and fixing some things by hand in 516b1385fa0e2405ba00f71b7be9958d2beba1a5 resolves most of the issues mentioned.

The only remaining one is
```
- ref 3: arxiv should be within []
```
which I don't know how to change, but also thing is not very important.
(pull request changing this or other formatting issues is welcome of course)
