### ISSUE TITLE
Suggestions by Lars on poster

### ISSUE THREAD

**Issue by cdeil** [gammapy/icrc2017-gammapy-poster#3]
@larsmohrmann comments on the poster via mail: the text is hard to read. suggests to change to a serif font and / or reduce text and increase size of figures.

**Comment by cdeil** [comment]
The layout and font is the one from the CTA poster template. It's used by most CTA posters. I'm not a fan, but for this poster would suggest we get with the program and keep their layout / fonts.

Agree that text should be reduced a bit and Figure sizes increased. I'll have a look, but concrete suggestions what to shorten or remove are welcome of course.

**Comment by lmohrmann** [comment]
Suggestion for the "Behind the scenes..." section:

Figure 2 shows a Gammapy code example that generates a counts image from an event list. The remarkable point here is that all data are stored in Numpy arrays and processed efficiently via calls into existing C extensions in Numpy and Astropy. For instance, in the example, the EventList and SkyImage objects store coordinates and pixel data as Numpy arrays, respectively. Data processing routines such as image.fill(events) are based on Numpy histograms and calls into the CFITSIO and WCSLib C libraries. Should the case occur that an algorithm cannot be efficiently implemented in pure Python, a small C extension can be added (using e.g. Cython).

**Comment by cdeil** [comment]
Here's a new draft for the poster:
https://github.com/gammapy/icrc2017-gammapy-poster/blob/master/poster/icrc2017-gammapy-poster-v2.pdf

@lmohrmann - Thanks for the feedback and the text proposal above.

I'm closing this issue now, let's continue the discussion on the poster in #5 .
